ci:
  config:
    schema_version: 1
    trunk_branch: main
    environments:
      - dev
      - staging
      - prod
    cli_version: v1.1.2-rc.0
    cli_version_sha: 3742e04377b952a263bb48a0a0bb5905c253d603
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    shared_paths:
      - libs/common/**
    components:
      api:
        path: services/api
        tag_grammar:
          prefix: api-
        builds:
          - name: api
            workflow: .github/workflows/build-api.yaml
            triggers:
              - services/api/**
        deploys:
          - name: api
            workflow: .github/workflows/deploy-api.yaml
            triggers:
              - services/api/**
      web:
        path: apps/web
        tag_grammar:
          prefix: web-
        builds:
          - name: web
            workflow: .github/workflows/build-web.yaml
            triggers:
              - apps/web/**
        deploys:
          - name: web
            workflow: .github/workflows/deploy-web.yaml
            triggers:
              - apps/web/**
  state:
    components:
      api:
        dev:
          sha: 741be0ec11e21baa4092654d204b68bc5cb4809c
          version: api-0.2.0-rc.0
          committed_at: "2026-10-05T06:58:59Z"
          committed_by: joshua-temple
          deploys:
            api:
              sha: 741be0ec11e21baa4092654d204b68bc5cb4809c
              deployed_at: "2026-10-05T06:58:59Z"
              deployed_by: joshua-temple
        staging:
          sha: 2a33a9a74f54c8c7ecc516f9a325eb78fd7dfd94
          version: api-0.1.0-rc.0
          committed_at: "2026-10-05T06:52:56Z"
          committed_by: joshua-temple
          deploys:
            api:
              sha: 2a33a9a74f54c8c7ecc516f9a325eb78fd7dfd94
              version: api-0.1.0-rc.0
              deployed_at: "2026-10-05T06:52:56Z"
              deployed_by: joshua-temple
        release:
          sha: 2a33a9a74f54c8c7ecc516f9a325eb78fd7dfd94
          version: api-0.1.0
          committed_at: "2026-10-05T06:54:01Z"
          committed_by: joshua-temple
        prod:
          sha: 2a33a9a74f54c8c7ecc516f9a325eb78fd7dfd94
          version: api-0.1.0
          committed_at: "2026-10-05T06:54:01Z"
          committed_by: joshua-temple
          deploys:
            api:
              sha: 2a33a9a74f54c8c7ecc516f9a325eb78fd7dfd94
              version: api-0.1.0
              deployed_at: "2026-10-05T06:54:01Z"
              deployed_by: joshua-temple
      web:
        dev:
          sha: ff9aa130286de5e725d3c399cc936187d8e7830b
          version: web-0.1.0-rc.0
          committed_at: "2026-10-05T06:55:23Z"
          committed_by: joshua-temple
          deploys:
            web:
              sha: ff9aa130286de5e725d3c399cc936187d8e7830b
              deployed_at: "2026-10-05T06:55:23Z"
              deployed_by: joshua-temple
        staging:
          sha: ff9aa130286de5e725d3c399cc936187d8e7830b
          version: web-0.1.0-rc.0
          committed_at: "2026-10-05T06:56:27Z"
          committed_by: joshua-temple
          deploys:
            web:
              sha: ff9aa130286de5e725d3c399cc936187d8e7830b
              version: web-0.1.0-rc.0
              deployed_at: "2026-10-05T06:56:27Z"
              deployed_by: joshua-temple
        release:
          sha: ff9aa130286de5e725d3c399cc936187d8e7830b
          version: web-0.1.0
          committed_at: "2026-10-05T06:57:33Z"
          committed_by: joshua-temple
        prod:
          sha: ff9aa130286de5e725d3c399cc936187d8e7830b
          version: web-0.1.0
          committed_at: "2026-10-05T06:57:33Z"
          committed_by: joshua-temple
          deploys:
            web:
              sha: ff9aa130286de5e725d3c399cc936187d8e7830b
              version: web-0.1.0
              deployed_at: "2026-10-05T06:57:33Z"
              deployed_by: joshua-temple
  latest_release:
    components:
      api:
        version: api-0.1.0
        sha: 2a33a9a74f54c8c7ecc516f9a325eb78fd7dfd94
        released_on: "2026-10-05T06:54:01Z"
      web:
        version: web-0.1.0
        sha: ff9aa130286de5e725d3c399cc936187d8e7830b
        released_on: "2026-10-05T06:57:33Z"
